---
title: "Summary"
Author: Naboni Thomas Kidane
format:
  html:
    code-fold: true
jupyter: python3
---

---
# Week 2

# SE1

## Summary

The book discusses the differences between software engineering, programming, and computer science. Software engineering is more serious and involves applying theoretical knowledge to create something tangible. Software engineering practices are not as rigorous as other engineering fields, but the need for more rigorous methods is increasing. Software engineering includes writing code and using tools and processes to maintain it over time. The book emphasizes three principles for software organizations: Time and Change, Scale and Growth, and Trade-offs and Costs.

# Reflection

After reading the book ‘Software Engineering’, I learned about the distinction between programming and software engineering. I didn’t know that they were related but they do different things for the same product. The field of software engineering involves rigorous methods such as running test cases for a program by writing code, which I believe most engineering fields don’t do.

# Use-case 
By using the skills from software engineering and considering the trade-offs and benefits, I would benefit in shaping up my skills and gain more understanding of it.



# FB1

# Summary

# Reflection

# Use-case
